export enum ActionTypes {
  MESSAGE_LOAD_REQUEST = 'ActionTypes::MESSAGE_LOAD_REQUEST',
  MESSAGE_LOAD_SUCCESS = 'ActionTypes::MESSAGE_LOAD_SUCCESS',
  MESSAGE_LOAD_FAILURE = 'ActionTypes::MESSAGE_LOAD_FAILURE',
  TASK_LOAD_REQUEST = 'ActionTypes::TASK_LOAD_REQUEST',
  TASK_LOAD_SUCCESS = 'ActionTypes::TASK_LOAD_SUCCESS',
  TASK_LOAD_FAILURE = 'ActionTypes::TASK_LOAD_FAILURE'
}
